
snippet_support = false
verbosity = 2


[server]
timeout = 600 # seconds = 10 minutes


[language.c_cpp]
filetypes = ["c", "cpp"]
roots = ["compile_commands.json", ".clangd"]
command = "clangd"


[language.python]
filetypes = ["python"]
roots = ["requirements.txt", "setup.py", ".git", ".hg"]
command = "pyls"
offset_encoding = "utf-8"


[language.go]
filetypes = ["go"]
roots = ["Gopkg.toml", "go.mod", ".git", ".hg"]
command = "gopls"
offset_encoding = "utf-8"


## Commented out by default because you still need to set the paths in the JDT
## Language Server arguments below before this can become a valid configuration.
#[language.java]
#filetypes = ["java"]
#roots = [".git", "mvnw", "gradlew"]
#command = "java"
#args = [
#    "-Declipse.application=org.eclipse.jdt.ls.core.id1",
#    "-Dosgi.bundles.defaultStartLevel=4",
#    "-Declipse.product=org.eclipse.jdt.ls.core.product",
#    "-Dlog.level=ALL",
#    "-Dfile.encoding=utf-8",
#    "--add-modules=ALL-SYSTEM",
#    "--add-opens",
#    "java.base/java.util=ALL-UNNAMED",
#    "--add-opens",
#    "java.base/java.lang=ALL-UNNAMED",
#    "-noverify",
#    "-Xmx1G",
#    "-jar",
#    "/home/faraday/.local/share/eclipse.jdt/plugins/org.eclipse.equinox.launcher_1.6.200.v20210416-2027.jar",
#    "-configuration",
#    "/home/faraday/.local/share/eclipse.jdt/config_linux/",
#    "-data",
#    "/home/faraday/.local/share/eclipse.jdt/"
#]

